export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SAVE_CATEGORIES = "SAVE_CATEGORIES";
export const SAVE_ARTICLES = "SAVE_ARTICLES";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const SAVE_AUTHOR = "SAVE_AUTHOR";
export const SAVE_LATEST_ARTICLE = "SAVE_LATEST_ARTICLE";
export const FETCH_MORE_ARTICLE = "FETCH_MORE_ARTICLE"; 
export const INCREMENT_PAGE_COUNT = "INCREMENT_PAGE_COUNT";
// data loading status;

export const DATA_NOT_AVAILABLE = 'DATA_NOT_AVAILABLE';
export const DATA_LOAD_TOGGLE = 'DATA_LOAD_TOGGLE';

export const RESET_PAGE_COUNT = 'RESET_PAGE_COUNT';
export const RESET_CATEGORY_ARTICLES = 'RESET_CATEGORY_ARTICLES';

export const SAVE_TOP_ARTICLES = 'SAVE_TOP_ARTICLES';
export const SAVE_SIMILAR_ARTICLES = 'SAVE_SIMILAR_ARTICLES';